language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --pre --dev --deploy

script: 
  - pipenv run check
  - pipenv run test
  
branch:
  - master
  - develop
